version: '3.1'

services:

 db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: 1234

 phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80

volumes:
  dbbase: